<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Student;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'first_name' => 'mohammad',
                'last_name' => 'ali',
                'birthdate' => '2010-06-23',
                'email' => 'ibrahim.keddah@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099111411',
                'address' => 'damascus',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'nour',
                'last_name' => 'amr',
                'birthdate' => '2010-02-15',
                'email' => 'nooramr@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12344321'),
                'gender' => 'female',
                'role' => 'student',
                'phone' => '099111113',
                'address' => 'damascus',
                "profile_picture_path" => "/storage/images/default_female_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'ali',
                'last_name' => 'hamed',
                'birthdate' => '2010-07-10',
                'email' => 'alihamed@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099111115',
                'address' => 'damascus',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'waten',
                'last_name' => 'mohammad',
                'birthdate' => '2010-04-25',
                'email' => 'waten@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'gender' => 'female',
                'role' => 'student',
                'phone' => '099111117',
                'address' => 'damascus',
                "profile_picture_path" => "/storage/images/default_female_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'danial',
                'last_name' => 'aboud',
                'birthdate' => '2010-09-18',
                'email' => 'daneab@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('1234554321'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099111119',
                'address' => 'damascus',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'sharef',
                'birthdate' => '2010-11-30',
                'email' => 'sarah@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11223344'),
                'gender' => 'female',
                'role' => 'student',
                'phone' => '099111122',
                'address' => 'damascus',
                "profile_picture_path" => "/storage/images/default_female_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Jamel',
                'last_name' => 'yacin',
                'birthdate' => '2010-06-20',
                'email' => 'jamel@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099111124',
                'address' => 'damascus',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'yosef',
                'last_name' => 'soboh',
                'birthdate' => '2010-03-12',
                'email' => 'yosef@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12344321'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099111126',
                'address' => 'damasucs',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'ahmed',
                'last_name' => 'aboud',
                'birthdate' => '2010-08-05',
                'email' => 'aboudahmed@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('54321'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099111178',
                'address' => 'daraa',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'marya',
                'last_name' => 'omran',
                'birthdate' => '2010-08-25',
                'email' => 'marya@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('1234554321'),
                'gender' => 'female',
                'role' => 'student',
                'phone' => '099111131',
                'address' => 'daraa',
                "profile_picture_path" => "/storage/images/default_female_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'samar',
                'last_name' => 'hbous',
                'birthdate' => '2010-09-06',
                'email' => 'samar@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('54321'),
                'gender' => 'female',
                'role' => 'student',
                'phone' => '099111183',
                'address' => 'daraa',
                "profile_picture_path" => "/storage/images/default_female_picture.jp",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'ahmed',
                'last_name' => 'ahmed',
                'birthdate' => '2010-03-15',
                'email' => 'ahmedahmed@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('5432154321'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099111133',
                'address' => 'daraa',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'saleh',
                'last_name' => 'nader',
                'birthdate' => '2010-07-18',
                'email' => 'saleh@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('54321'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099111145',
                'address' => 'daraa',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'huda',
                'last_name' => 'ibrahem',
                'birthdate' => '2010-12-05',
                'email' => 'huda@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('54321'),
                'gender' => 'female',
                'role' => 'student',
                'phone' => '099111158',
                'address' => 'daraa',
                "profile_picture_path" => "/storage/images/default_female_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'ghaedaa',
                'last_name' => 'salem',
                'birthdate' => '2010-03-29',
                'email' => 'ghaedaa@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('54321'),
                'gender' => 'female',
                'role' => 'student',
                'phone' => '099111321',
                'address' => 'damasucs',
                "profile_picture_path" => "/storage/images/default_female_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'ahmed',
                'last_name' => 'naser',
                'birthdate' => '2010-11-05',
                'email' => 'naserahmed@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('123456'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099141128',
                'address' => 'daraa',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'khaled',
                'last_name' => 'faker',
                'birthdate' => '2010-06-25',
                'email' => 'khaledfaker@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('1234554321'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099111128',
                'address' => 'daraa',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'omran',
                'last_name' => 'salah',
                'birthdate' => '2010-07-21',
                'email' => 'omran@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('54321'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '099114528',
                'address' => 'daraa',
                "profile_picture_path" => "/storage/images/default_male_picture.jp",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'zahra',
                'last_name' => 'aboud',
                'birthdate' => '2010-10-12',
                'email' => 'zahra@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('112233'),
                'gender' => 'female',
                'role' => 'student',
                'phone' => '099111338',
                'address' => 'daraa',
                "profile_picture_path" => "/storage/images/default_female_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'deaa',
                'last_name' => 'merai',
                'birthdate' => '2010-11-09',
                'email' => 'deaamerai@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('87654321'),
                'gender' => 'male',
                'role' => 'student',
                'phone' => '0991111558',
                'address' => 'damasucs',
                "profile_picture_path" => "/storage/images/default_male_picture.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert users into 'users' table
        DB::table('users')->insert($users);

        // Seed students
        $students = [
            [
                'user_id' => User::where('email', 'ibrahim.keddah@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 0,
                'enrollment_date' => now(),  // Example enrollment date, adjust as needed
                'parent_name' => 'kasem.',
                'parent_phone' => '099111112',
                'parent_email' => 'kasemali@gmail.com',
                'bus' => '0',
                'remain'=>450000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'nooramr@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 130000,
                'enrollment_date' => now(),  // Example enrollment date, adjust as needed
                'parent_name' => 'ahmed.',
                'parent_phone' => '099111114',
                'parent_email' => 'ahmedamr@gmail.com',
                'bus' => '0',
                'remain'=>450000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'alihamed@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 10000,
                'enrollment_date' => now()->subDays(3),  // Example enrollment date, adjust as needed
                'parent_name' => ' morad hamed.',
                'parent_phone' => '099111116',
                'parent_email' => 'moradhamed@gmail.com',
                'bus' => '0',
                'remain'=>450000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'waten@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 200000,
                'enrollment_date' => now()->subDays(5),  // Example enrollment date, adjust as needed
                'parent_name' => ' amar.',
                'parent_phone' => '099111118',
                'parent_email' => 'amarmo@example.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'daneab@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 20000,
                'enrollment_date' => now()->subDays(3),  // Example enrollment date, adjust as needed
                'parent_name' => 'nezar.',
                'parent_phone' => '099111121',
                'parent_email' => 'nezarab@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'sarah@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 0,
                'enrollment_date' => now()->subDays(4),  // Example enrollment date, adjust as needed
                'parent_name' => 'owais.',
                'parent_phone' => '099111123',
                'parent_email' => 'owaisab@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'jamel@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 50000,
                'enrollment_date' => now()->subDays(8),  // Example enrollment date, adjust as needed
                'parent_name' => 'mohammad.',
                'parent_phone' => '099111125',
                'parent_email' => 'moyacin@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'yosef@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 123000,
                'enrollment_date' => now()->subDays(5),  // Example enrollment date, adjust as needed
                'parent_name' => 'khaled.',
                'parent_phone' => '099111127',
                'parent_email' => 'khaled@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'aboudahmed@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 0,
                'enrollment_date' => now()->subDays(10),  // Example enrollment date, adjust as needed
                'parent_name' => 'ramze.',
                'parent_phone' => '099111129',
                'parent_email' => 'ramzi@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'marya@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 20000,
                'enrollment_date' => now()->subDays(10),  // Example enrollment date, adjust as needed
                'parent_name' => 'hamza.',
                'parent_phone' => '099111132',
                'parent_email' => 'hamza@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'samar@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 10000,
                'enrollment_date' => now()->subDays(10),  // Example enrollment date, adjust as needed
                'parent_name' => 'abdallah.',
                'parent_phone' => '099111134',
                'parent_email' => 'abdallah@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'ahmedahmed@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 0,
                'enrollment_date' => now()->subDays(10),  // Example enrollment date, adjust as needed
                'parent_name' => 'hani.',
                'parent_phone' => '099111136',
                'parent_email' => 'hani@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'saleh@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 0,
                'enrollment_date' => now()->subDays(10),  // Example enrollment date, adjust as needed
                'parent_name' => 'ahmed.',
                'parent_phone' => '099111144',
                'parent_email' => 'ahmadna@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'huda@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 0,
                'enrollment_date' => now()->subDays(1),  // Example enrollment date, adjust as needed
                'parent_name' => 'ali.',
                'parent_phone' => '099111222',
                'parent_email' => 'alosh@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'ghaedaa@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 0,
                'enrollment_date' => now()->subDays(2),  // Example enrollment date, adjust as needed
                'parent_name' => 'majd.',
                'parent_phone' => '099111469',
                'parent_email' => 'majd@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'naserahmed@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 0,
                'enrollment_date' => now()->subDays(11),  // Example enrollment date, adjust as needed
                'parent_name' => 'mosa.',
                'parent_phone' => '099112119',
                'parent_email' => 'mosa@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'khaledfaker@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 100000,
                'enrollment_date' => now()->subDays(2),  // Example enrollment date, adjust as needed
                'parent_name' => 'ahmed.',
                'parent_phone' => '099111888',
                'parent_email' => 'ahmedfaker@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'omran@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 60000,
                'enrollment_date' => now()->subDays(10),  // Example enrollment date, adjust as needed
                'parent_name' => 'zaher',
                'parent_phone' => '099111192',
                'parent_email' => 'zaler@gmail.com',
                'bus' => '0',
                'remain'=>450000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'zahra@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 100000,
                'enrollment_date' => now()->subDays(15),  // Example enrollment date, adjust as needed
                'parent_name' => 'sami.',
                'parent_phone' => '099121212',
                'parent_email' => 'samiab@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'deaamerai@gmail.com')->first()->id,
                'class_id' => 1, // Replace with actual class_id from 'classes' table
                'wallet_balance' => 0,
                'enrollment_date' => now()->subDays(10),  // Example enrollment date, adjust as needed
                'parent_name' => 'nasri.',
                'parent_phone' => '099551129',
                'parent_email' => 'nasri@gmail.com',
                'bus' => '1',
                'remain'=>495000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert students into 'students' table
        DB::table('students')->insert($students);
    }
}
