<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class Subject_units extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('subject_units')->insert([
            //------7------
            [
                'subject_id' => 1,
                'unit_number' => 1,
                'title' => 'Belonging and citizenship',
                'description' => 'more teaching on belonging and citizenship.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 1,
                'unit_number' => 2,
                'title' => 'Arts & Culture',
                'description' => 'more teaching on arts and culture .',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 1,
                'unit_number' => 3,
                'title' => 'Youth Issues',
                'description' => ' more teaching on Youth Issues.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 2,
                'unit_number' => 1,
                'title' => 'the cell',
                'description' => 'more teaching on the cell.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 2,
                'unit_number' => 2,
                'title' => 'The origin of the evolution of biology',
                'description' => 'more teaching on The origin of the evolution of biology .',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'subject_id' => 2,
                'unit_number' => 3,
                'title' => 'plant life',
                'description' => 'more teaching on plant life.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 235837.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 3,
                'unit_number' => 1,
                'title' => 'physics',
                'description' => 'more teaching on Movement & Animation.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 3,
                'unit_number' => 2,
                'title' => 'chemistry',
                'description' => 'more teaching on subject and temprature .',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 4,
                'unit_number' => 1,
                'title' => 'numbers and operation',
                'description' => 'more teaching on numbers and operation .',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 4,
                'unit_number' => 2,
                'title' => 'algebra statement and equalations',
                'description' => 'more teaching on algebra statement and equalations.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'subject_id' => 5,
                'unit_number' => 1,
                'title' => 'Algorthim programming ',
                'description' => 'more teaching on Algorthim programming ',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 5,
                'unit_number' => 2,
                'title' => ' app programming',
                'description' => 'more teaching on app programming .',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 6,
                'unit_number' => 1,
                'title' => 'student book',
                'description' => 'more teaching on french language.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 6,
                'unit_number' => 2,
                'title' => 'activity book',
                'description' => 'more exercise for Reinforcement.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 7,
                'unit_number' => 1,
                'title' => 'student book',
                'description' => 'more teaching on english language.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 7,
                'unit_number' => 2,
                'title' => 'Activity book',
                'description' => 'more exercise for Reinforcement .',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 8,
                'unit_number' => 1,
                'title' => 'history',
                'description' => 'old syria .',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 9,
                'unit_number' => 1,
                'title' => 'geography',
                'description' => ' .',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 10,
                'unit_number' => 1,
                'title' => ' National education',
                'description' => ' more on Syrian National.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 11,
                'unit_number' => 1,
                'title' => 'Great reward',
                'description' => 'Great reward.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 11,
                'unit_number' => 2,
                'title' => 'The value of the martyr ',
                'description' => 'The value of the martyr.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
           //-----8-------

            [
            'subject_id' => 9,
            'unit_number' => 1,
            'title' => 'Belonging and citizenship',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 9,
            'unit_number' => 2,
            'title' => 'Arts & Culture',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 9,
            'unit_number' => 3,
            'title' => 'Youth Issues',
            'description' => ' more teaching on Youth Issues.',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 10,
            'unit_number' => 1,
            'title' => 'Science',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 10,
            'unit_number' => 2,
            'title' => 'physics and chemistry',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'subject_id' => 11,
            'unit_number' => 1,
            'title' => 'algebra',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 11,
            'unit_number' => 2,
            'title' => 'Engineering',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 12,
            'unit_number' => 1,
            'title' => 'computer structure',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 12,
            'unit_number' => 2,
            'title' => 'programming',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 13,
            'unit_number' => 1,
            'title' => 'student book',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 13,
            'unit_number' => 2,
            'title' => 'activity book',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 14,
            'unit_number' => 1,
            'title' => 'student book',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 14,
            'unit_number' => 2,
            'title' => 'Activity book',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 15,
            'unit_number' => 1,
            'title' => 'history',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 15,
            'unit_number' => 2,
            'title' => 'geography',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 15,
            'unit_number' => 3,
            'title' => ' National education',
            'description' => ' more teaching on Youth Issues.',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 16,
            'unit_number' => 1,
            'title' => 'islam Principles',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ]);
    }
}
