<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class Subject extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('subjects')->insert([
            [
                'name' => 'arabic',
                'the_class' => '7',
                'total_grade' => 600,
                'about_subject' => 'Introduction to Arabic language.',
                "book_path"=>"/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 113627.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Science',
                'the_class' => '7',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic science concepts.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 145439.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Physics and chemistry ',
                'the_class' => '7',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic Physics and chemistry concepts.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 145439.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mathematics',
                'the_class' => '7',
                'total_grade' => 600,
                'about_subject' => 'Introduction to basic mathematics concepts.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 145734.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'information technology',
                'the_class' => '7',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic information technology.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150024.png",
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'name' => 'french',
                'the_class' => '7',
                'total_grade' => 300,
                'about_subject' => 'Introduction to basic french language.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'english',
                'the_class' => '7',
                'total_grade' => 400,
                'about_subject' => 'Introduction to basic english language.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'history',
                'the_class' => '7',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic history .',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'geography',
                'the_class' => '7',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic geography .',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'National education ',
                'the_class' => '7',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic National education  .',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'islamic religious',
                'the_class' => '7',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic  islamic religious.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'arabic',
                'the_class' => '8',
                'total_grade' => 600,
                'about_subject' => 'Introduction to Arabic language.',
                "book_path"=>"/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 113627.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Science',
                'the_class' => '8',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic science concepts.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 145439.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Physics and chemistry ',
                'the_class' => '8',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic Physics and chemistry concepts.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 145439.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mathematics',
                'the_class' => '8',
                'total_grade' => 600,
                'about_subject' => 'Introduction to basic mathematics concepts.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 145734.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'information technology',
                'the_class' => '8',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic information technology.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150024.png",
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'name' => 'french',
                'the_class' => '8',
                'total_grade' => 300,
                'about_subject' => 'Introduction to basic french language.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'english',
                'the_class' => '8',
                'total_grade' => 400,
                'about_subject' => 'Introduction to basic english language.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'history',
                'the_class' => '8',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic history .',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'geography',
                'the_class' => '8',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic geography .',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'National education ',
                'the_class' => '8',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic National education  .',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'islamic religious',
                'the_class' => '8',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic  islamic religious.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'name' => 'arabic',
                'the_class' => '9',
                'total_grade' => 600,
                'about_subject' => 'Introduction to Arabic language.',
                "book_path"=>"/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 113627.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Science',
                'the_class' => '9',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic science concepts.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 145439.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Physics and chemistry ',
                'the_class' => '9',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic Physics and chemistry concepts.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 145439.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mathematics',
                'the_class' => '9',
                'total_grade' => 600,
                'about_subject' => 'Introduction to basic mathematics concepts.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 145734.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'information technology',
                'the_class' => '9',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic information technology.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150024.png",
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'name' => 'french',
                'the_class' => '9',
                'total_grade' => 300,
                'about_subject' => 'Introduction to basic french language.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'english',
                'the_class' => '9',
                'total_grade' => 400,
                'about_subject' => 'Introduction to basic english language.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'history',
                'the_class' => '9',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic history .',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'geography',
                'the_class' => '9',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic geography .',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'National education ',
                'the_class' => '9',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic National education  .',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'islamic religious',
                'the_class' => '9',
                'total_grade' => 200,
                'about_subject' => 'Introduction to basic  islamic religious.',
                "book_path"=> "/storage/images/project1Report00.pdf",
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 150127.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        
        ]);
    }
}
