<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class Subject_units extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('subject_units')->insert([
            //------7------
            [
                'subject_id' => 1,
                'unit_number' => 1,
                'title' => 'Belonging and citizenship',
                'description' => 'more teaching on belonging and citizenship.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 180657.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 1,
                'unit_number' => 2,
                'title' => 'Arts & Culture',
                'description' => 'more teaching on arts and culture .',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 180735.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 1,
                'unit_number' => 3,
                'title' => 'Youth Issues',
                'description' => ' more teaching on Youth Issues.',
                "photo_path"=> "/storage/images/Screenshots\Screenshot 2024-08-16 180815.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 2,
                'unit_number' => 1,
                'title' => 'Science',
                'description' => 'more teaching on belonging and citizenship.',
                "photo_path"=> "/storage/images/Screenshot 2024-08-16 145439.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 2,
                'unit_number' => 2,
                'title' => 'physics and chemistry',
                'description' => 'more teaching on arts and culture .',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'subject_id' => 3,
                'unit_number' => 1,
                'title' => 'algebra',
                'description' => 'more teaching on algebra.',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 3,
                'unit_number' => 2,
                'title' => 'Engineering',
                'description' => 'more teaching on the engineering .',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 4,
                'unit_number' => 1,
                'title' => 'computer structure',
                'description' => 'more teaching on computer structure',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 4,
                'unit_number' => 2,
                'title' => 'programming',
                'description' => 'more teaching on programming .',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 5,
                'unit_number' => 1,
                'title' => 'student book',
                'description' => 'more teaching on french language.',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 5,
                'unit_number' => 2,
                'title' => 'activity book',
                'description' => 'more exercise for Reinforcement.',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 6,
                'unit_number' => 1,
                'title' => 'student book',
                'description' => 'more teaching on english language.',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 6,
                'unit_number' => 2,
                'title' => 'Activity book',
                'description' => 'more exercise for Reinforcement .',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 7,
                'unit_number' => 1,
                'title' => 'history',
                'description' => 'the Arabic modern history .',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 7,
                'unit_number' => 2,
                'title' => 'geography',
                'description' => 'Topography of the Arab world .',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 7,
                'unit_number' => 3,
                'title' => ' National education',
                'description' => ' more on Syrian National.',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_id' => 8,
                'unit_number' => 1,
                'title' => 'islam Principles',
                'description' => 'teach how to be mislim.',
                "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
           //-----8-------

            [
            'subject_id' => 9,
            'unit_number' => 1,
            'title' => 'Belonging and citizenship',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 9,
            'unit_number' => 2,
            'title' => 'Arts & Culture',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 9,
            'unit_number' => 3,
            'title' => 'Youth Issues',
            'description' => ' more teaching on Youth Issues.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 10,
            'unit_number' => 1,
            'title' => 'Science',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 10,
            'unit_number' => 2,
            'title' => 'physics and chemistry',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'subject_id' => 11,
            'unit_number' => 1,
            'title' => 'algebra',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 11,
            'unit_number' => 2,
            'title' => 'Engineering',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 12,
            'unit_number' => 1,
            'title' => 'computer structure',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 12,
            'unit_number' => 2,
            'title' => 'programming',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 13,
            'unit_number' => 1,
            'title' => 'student book',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 13,
            'unit_number' => 2,
            'title' => 'activity book',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 14,
            'unit_number' => 1,
            'title' => 'student book',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 14,
            'unit_number' => 2,
            'title' => 'Activity book',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 15,
            'unit_number' => 1,
            'title' => 'history',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 15,
            'unit_number' => 2,
            'title' => 'geography',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 15,
            'unit_number' => 3,
            'title' => ' National education',
            'description' => ' more teaching on Youth Issues.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 16,
            'unit_number' => 1,
            'title' => 'islam Principles',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        //------9------
        [
            'subject_id' => 17,
            'unit_number' => 1,
            'title' => 'Belonging and citizenship',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 17,
            'unit_number' => 2,
            'title' => 'Arts & Culture',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 17,
            'unit_number' => 3,
            'title' => 'Youth Issues',
            'description' => ' more teaching on Youth Issues.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 18,
            'unit_number' => 1,
            'title' => 'Science',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 18,
            'unit_number' => 2,
            'title' => 'physics',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 18,
            'unit_number' => 3,
            'title' => 'chemistry',
            'description' => ' more teaching on Youth Issues.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 19,
            'unit_number' => 1,
            'title' => 'algebra',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 19,
            'unit_number' => 2,
            'title' => 'Engineering',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'subject_id' => 20,
            'unit_number' => 1,
            'title' => 'student book',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 20,
            'unit_number' => 2,
            'title' => 'activity book',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 21,
            'unit_number' => 1,
            'title' => 'student book',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 21,
            'unit_number' => 2,
            'title' => 'Activity book',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 22,
            'unit_number' => 1,
            'title' => 'history',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 22,
            'unit_number' => 2,
            'title' => 'geography',
            'description' => 'more teaching on arts and culture .',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' => 22,
            'unit_number' => 3,
            'title' => ' National education',
            'description' => ' more teaching on Youth Issues.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'subject_id' =>23,
            'unit_number' => 1,
            'title' => 'islam Principles',
            'description' => 'more teaching on belonging and citizenship.',
            "photo_path"=> "/storage/images/xARTOr06WbwFbSfQOrA7WbzhBlAh9bSsuPxSCqLa.jpg",
            'created_at' => now(),
            'updated_at' => now(),
        ],

        ]);
    }
}
