<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\teacher;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'first_name' => 'rami',
                'last_name' => 'aboud',
                'birthdate' => '1992-10-21',
                'email' => 'ramiab@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('112233'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0936321321',
                'address' => 'ghabagheb',
                "profile_picture_path"=> "/storage/images/photo_2024-07-24_22-12-02.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'nezar',
                'last_name' => 'oweidat',
                'birthdate' => '1964-03-11',
                'email' => 'nezar@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0999777111',
                'address' => 'Damascus City',
                "profile_picture_path"=> "/storage/image/photo_2024-08-01_13-31-18.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'mohsen',
                'last_name' => 'alkhateeb',
                'birthdate' => '1980-02-15',
                'email' => 'mohsen@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('112233'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0936936936',
                'address' => 'damasucs',
                "profile_picture_path"=> "/storage/image/photo_2024-08-01_13-31-30.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'mohammad',
                'last_name' => 'salama',
                'birthdate' => '1994-02-15',
                'email' => 'mosalama@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('112233'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0936123123',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/photo_2024-07-24_22-11-57.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'ali',
                'last_name' => 'mansor',
                'birthdate' => '1992-03-10',
                'email' => 'alimansor@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('11223344'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0936123444',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/photo_2024-07-24_22-12-10.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'reaad',
                'last_name' => 'salman',
                'birthdate' => '1991-12-19',
                'email' => 'reaad@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('222333'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0987451451',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/photo_2024-07-24_22-11-45.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'ola',
                'last_name' => 'jamal',
                'birthdate' => '1990-02-18',
                'email' => 'olajamal@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('112233'),
                'gender' => 'female',
                'role' => 'teacher',
                'phone' => '0993621621',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/photo_2024-08-01_13-31-58.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'mohammad',
                'last_name' => 'emam',
                'birthdate' => '1992-06-01',
                'email' => 'moemam@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('112233'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0993621231',
                'address' => 'alkeswah',
                "profile_picture_path"=> "/storage/images/photo_2024-08-01_13-31-34.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'ahmed',
                'last_name' => 'kamel',
                'birthdate' => '1993-09-03',
                'email' => 'ahmedkamel@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('112233'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0993525231',
                'address' => 'homs',
                "profile_picture_path"=> "/storage/images/photo_2024-08-01_13-31-54.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'rita',
                'last_name' => 'al-shokor',
                'birthdate' => '1998-11-19',
                'email' => 'ritaalshokor@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12344321'),
                'gender' => 'female',
                'role' => 'teacher',
                'phone' => '0958515224',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/rita.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'sameha',
                'last_name' => 'nasr',
                'birthdate' => '2000-02-17',
                'email' => 'samehansr@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'female',
                'role' => 'teacher',
                'phone' => '0982435919',
                'address' => 'alsuwayda',
                "profile_picture_path"=> "/storage/images/photo_2024-07-24_22-11-50.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'shereen',
                'last_name' => 'ahmed',
                'birthdate' => '1987-02-19',
                'email' => 'shereen@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('222333'),
                'gender' => 'female',
                'role' => 'teacher',
                'phone' => '0936123456',
                'address' => 'homs',
                "profile_picture_path"=> "/storage/images/photo_2024-07-24_22-11-50.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'ahmad',
                'last_name' => 'karaman',
                'birthdate' => '1994-07-08',
                'email' => 'ahmadka@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0993448448',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/photo_2024-07-24_22-11-40.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'moyaad',
                'last_name' => 'sami',
                'birthdate' => '1974-05-19',
                'email' => 'noor2salah2@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12344321'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0993448111',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/photo_2024-08-01_00-07-07.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'mahmoud',
                'last_name' => 'alhamui',
                'birthdate' => '1991-01-02',
                'email' => 'mahmoudhamui@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('222333'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0936936368',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/photo_2024-08-01_13-31-26.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'emam',
                'last_name' => 'abd alhadi',
                'birthdate' => '1984-12-25',
                'email' => 'emamabd@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('222333'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0936936101',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/photo_2024-08-01_13-31-22.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'salim',
                'last_name' => 'ahmed',
                'birthdate' => '1987-12-19',
                'email' => 'salimahmed@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('87654321'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0994525121',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/photo_2024-08-01_13-31-22.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'khaldoon',
                'last_name' => 'alsady',
                'birthdate' => '1988-01-19',
                'email' => 'khaldoonsady@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('1234567'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0936321777',
                'address' => 'daraa',
                "profile_picture_path"=> "/storage/images/photo_2024-07-24_22-12-07.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'deaa',
                'last_name' => 'kaddah',
                'birthdate' => '1997-12-01',
                'email' => 'deaaka@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('222333'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0993950014',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/photo_2024-08-01_13-31-46.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'hala',
                'last_name' => 'yassin',
                'birthdate' => '1991-12-19',
                'email' => 'halayassin@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('222333'),
                'gender' => 'female',
                'role' => 'teacher',
                'phone' => '0993950025',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/Picture1.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'raneem',
                'last_name' => 'salah',
                'birthdate' => '1993-01-01',
                'email' => 'raneemsalah@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('222333'),
                'gender' => 'female',
                'role' => 'teacher',
                'phone' => '0936221227',
                'address' => 'alswedaa',
                "profile_picture_path"=> "/storage/images/photo_2024-08-01_13-32-02.jpg",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'naden',
                'last_name' => 'ali',
                'birthdate' => '1994-04-06',
                'email' => 'nadenali@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('87654321'),
                'gender' => 'female',
                'role' => 'teacher',
                'phone' => '0921921922',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/Picture2.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'salma',
                'last_name' => 'saadi',
                'birthdate' => '1990-04-21',
                'email' => 'salma@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('1234321'),
                'gender' => 'female',
                'role' => 'teacher',
                'phone' => '0921921921',
                'address' => 'lattakia',
                "profile_picture_path"=> "/storage/images/Picture2.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'qusai',
                'last_name' => 'nabelsi',
                'birthdate' => '1990-04-21',
                'email' => 'qusai@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('1234321'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0921921001',
                'address' => 'lattakia',
                "profile_picture_path"=> "/storage/images/Picture2.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'kenan',
                'last_name' => 'asaad',
                'birthdate' => '1991-04-21',
                'email' => 'kenan@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('1234321'),
                'gender' => 'male',
                'role' => 'teacher',
                'phone' => '0921921002',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/Picture2.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'faten',
                'last_name' => 'haje',
                'birthdate' => '1988-04-21',
                'email' => 'faten@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('1234321'),
                'gender' => 'female',
                'role' => 'teacher',
                'phone' => '0921921003',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/Picture2.png",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'rawan',
                'last_name' => 'kalfa',
                'birthdate' => '1981-04-21',
                'email' => 'rawan@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('1234321'),
                'gender' => 'female',
                'role' => 'teacher',
                'phone' => '0921921004',
                'address' => 'damascus',
                "profile_picture_path"=> "/storage/images/Picture2.png",
                'created_at' => now(),
                'updated_at' => now(),
                ],
                    [
                        'first_name' => 'hadi',
                        'last_name' => 'sabbagh',
                        'birthdate' => '1981-03-11',
                        'email' => 'hadisabbag@gmail.com',
                        'email_verified_at' => now(),
                        'password' => Hash::make('1234321'),
                        'gender' => 'male',
                        'role' => 'teacher',
                        'phone' => '0921921005',
                        'address' => 'damascus',
                        "profile_picture_path"=> "/storage/images/Picture2.png",
                        'created_at' => now(),
                        'updated_at' => now(),
                        ],
                        [
                            'first_name' => 'fesal',
                            'last_name' => 'kaeed',
                            'birthdate' => '1997-03-11',
                            'email' => 'fesal@gmail.com',
                            'email_verified_at' => now(),
                            'password' => Hash::make('1234321'),
                            'gender' => 'male',
                            'role' => 'teacher',
                            'phone' => '0921921006',
                            'address' => 'damascus',
                            "profile_picture_path"=> "/storage/images/Picture2.png",
                            'created_at' => now(),
                            'updated_at' => now(),
                            ],
            //Add more users as needed
        ];

        // Insert users into 'users' table
        DB::table('users')->insert($users);

        // Seed teachers
        $teachers = [
            [
                'user_id' => User::where('email', 'ramiab@gmail.com')->first()->id,
                'rate' => 5,
                'hire_date' => '2022-09-09',  // Example hire date, adjust as needed
                'specialization' => 'arabic',
                'education' => 'Master on arabic',
                'salary' => 1000000,
                'about' => 'beacon of knowledge.',
                'class_level'=>'7',
                'cv'=>"/storage/images/arabic1.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'nezar@gmail.com')->first()->id,
                'rate' => 4,
                'hire_date' => '2017-09-10',  // Example hire date, adjust as needed
                'specialization' => 'arabic',
                'education' => 'Bachelor of arabic literature',
                'salary' => 1200000,
                'about' => 'educator of generation',
                'class_level'=>'8',
                'cv'=>"/storage/images/arabic2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'mohsen@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' => '1980-08-02',  // Example hire date, adjust as needed
                'specialization' => 'arabic',
                'education' => 'Master of arabic',
                'salary' => 1100000,
                'about' => 'teaching arabic mission and honestly.',
                'class_level'=>'9',
                'cv'=>"/storage/images/arabic3.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'mosalama@gmail.com')->first()->id,
                'rate' => 4,
                'hire_date' => '2023-09-09',  // Example hire date, adjust as needed
                'specialization' => 'english',
                'education' => 'Master of english',
                'salary' => 1000000,
                'about' => 'Teaching English in an innovative way.',
                'class_level'=>'7',
                'cv'=>"/storage/images/e1.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'alimansor@gmail.com')->first()->id,
                'rate' => 5,
                'hire_date' => '2022-09-01',  // Example hire date, adjust as needed
                'specialization' => 'english',
                'education' => 'Bachelor of english',
                'salary' => 1000000,
                'about' => 'Inspiring English teacher.',
                'class_level'=>'8',
                'cv'=>"/storage/images/e2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'reaad@gmail.com')->first()->id,
                'rate' => 2.5,
                'hire_date' =>'2022-08-29',  // Example hire date, adjust as needed
                'specialization' => 'english',
                'education' => 'Bachelor of english',
                'salary' => 1000000,
                'about' => 'Specialist in English Language Teaching.',
                'class_level'=>'9',
                'cv'=>"/storage/images/e3.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'olajamal@gmail.com')->first()->id,
                'rate' => 2.5,
                'hire_date' =>'2020-08-23',  // Example hire date, adjust as needed
                'specialization' => 'french',
                'education' => 'Bachelor of france language',
                'salary' => 1000000,
                'about' => 'your way to french',
                'class_level'=>'9',
                'cv'=>"/storage/images/france1.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'moemam@gmail.com')->first()->id,
                'rate' => 3.5,
                'hire_date' =>'2021-08-29',  // Example hire date, adjust as needed
                'specialization' => 'french',
                'education' => 'Bachelor of french',
                'salary' => 1000000,
                'about' => 'professor de francais.',
                'class_level'=>'8',
                'cv'=>"/storage/images/france2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'ahmedkamel@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2021-08-29',  // Example hire date, adjust as needed
                'specialization' => 'french',
                'education' => 'Bachelor of french',
                'salary' => 1000000,
                'about' => 'Specialist in french Language Teaching.',
                'class_level'=>'7',
                'cv'=>"/storage/images/france3.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'ritaalshokor@gmail.com')->first()->id,
                'rate' => 4.2,
                'hire_date' =>'2022-08-29',  // Example hire date, adjust as needed
                'specialization' => 'information technology',
                'education' => 'Bachelor of information technology',
                'salary' => 1000000,
                'about' => 'teacher of the future.',
                'class_level'=>'7',
                'cv'=>"/storage/images/it1.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'samehansr@gmail.com')->first()->id,
                'rate' => 5,
                'hire_date' =>'2022-08-29',  // Example hire date, adjust as needed
                'specialization' => 'infromation technology',
                'education' => 'Bachelor of information technology',
                'salary' => 1000000,
                'about' => 'digital age teacher.',
                'class_level'=>'8',
                'cv'=>"/storage/images/it2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'shereen@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2020-08-29',  // Example hire date, adjust as needed
                'specialization' => 'mathmatics',
                'education' => 'Bachelor of mathmatical',
                'salary' => 1000000,
                'about' => 'engineer of minds.',
                'class_level'=>'9',
                'cv'=>"/storage/images/math1.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'ahmadka@gmail.com')->first()->id,
                'rate' => 3.9,
                'hire_date' =>'2020-08-29',  // Example hire date, adjust as needed
                'specialization' => 'mathmatics',
                'education' => 'Bachelor of mathmatical',
                'salary' => 1000000,
                'about' => 'logical thinker.',
                'class_level'=>'8',
                'cv'=>"/storage/images/math2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'nooramr@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2020-09-09',  // Example hire date, adjust as needed
                'specialization' => 'mathmatics',
                'education' => 'master of mathmatical',
                'salary' => 1000000,
                'about' => 'the godfather of maths.',
                'class_level'=>'7',
                'cv'=>"/storage/images/math3.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'mahmoudhamui@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2021-08-30',  // Example hire date, adjust as needed
                'specialization' => 'religious',
                'education' => 'Bachelor of religious',
                'salary' => 1000000,
                'about' => 'source of inspiration for students.',
                'class_level'=>'7',
                'cv'=>"/storage/images/religious1.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'emamabd@gmail.com')->first()->id,
                'rate' => 4.1,
                'hire_date' =>'2021-08-26',  // Example hire date, adjust as needed
                'specialization' => 'islamic literature',
                'education' => 'Bachelor of religious',
                'salary' => 1000000,
                'about' => 'Religious education with moral values.',
                'class_level'=>'8',
                'cv'=>"/storage/images/religious2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'salimahmed@gmail.com')->first()->id,
                'rate' => 4,
                'hire_date' =>'2022-08-25',  // Example hire date, adjust as needed
                'specialization' => 'islamic literature',
                'education' => 'Bachelor of english',
                'salary' => 1000000,
                'about' => 'Specialist in islamic literature.',
                'class_level'=>'9',
                'cv'=>"/storage/images/religious3.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'khaldoonsady@gmail.com')->first()->id,
                'rate' => 5,
                'hire_date' =>'2022-09-02',  // Example hire date, adjust as needed
                'specialization' => 'science',
                'education' => 'Bachelor of science',
                'salary' => 1000000,
                'about' => 'Expert in teaching modern science.',
                'class_level'=>'9',
                'cv'=>"/storage/images/science1.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'deaaka@gmail.com')->first()->id,
                'rate' => 3.5,
                'hire_date' =>'2021-09-2',  // Example hire date, adjust as needed
                'specialization' => 'science',
                'education' => 'Bachelor of science',
                'salary' => 1000000,
                'about' => 'Specialist in  science Teaching.',
                'class_level'=>'8',
                'cv'=>"/storage/images/science2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'halayassin@gmail.com')->first()->id,
                'rate' => 3.7,
                'hire_date' =>'2022-08-10',  // Example hire date, adjust as needed
                'specialization' => 'science',
                'education' => 'Bachelor of science',
                'salary' => 1000000,
                'about' => 'Inspiring science teacher.',
                'class_level'=>'7',
                'cv'=>"/storage/images/science3.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'raneemsalah@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2020-08-29',  // Example hire date, adjust as needed
                'specialization' => 'history',
                'education' => 'Bachelor of history',
                'salary' => 1000000,
                'about' => 'Bringing the Past to Life.',
                'class_level'=>'9',
                'cv'=>"/storage/images/social1.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'nadenali@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2020-08-01',  // Example hire date, adjust as needed
                'specialization' => 'history',
                'education' => 'Bachelor of history',
                'salary' => 1000000,
                'about' => 'Specialist in History Education.',
                'class_level'=>'8',
                'cv'=>"/storage/images/social2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => User::where('email', 'salma@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2022-08-09',  // Example hire date, adjust as needed
                'specialization' => 'history',
                'education' => 'Bachelor of history',
                'salary' => 1000000,
                'about' => 'Guiding Students Through Time.',
                'class_level'=>'7',
                'cv'=>"/storage/images/social3.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'qusai@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2022-08-09',  // Example hire date, adjust as needed
                'specialization' => 'russian',
                'education' => 'Bachelor of russian',
                'salary' => 1000000,
                'about' => 'Guiding Students Through Time.',
                'class_level'=>'7',
                'cv'=>"/storage/images/france2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'kenan@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2022-08-09',  // Example hire date, adjust as needed
                'specialization' => 'geography',
                'education' => 'Bachelor of geography',
                'salary' => 1000000,
                'about' => 'Guiding Students Through Time.',
                'class_level'=>'7',
                'cv'=>"/storage/images/social3.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'faten@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2022-09-09',  // Example hire date, adjust as needed
                'specialization' => 'national education',
                'education' => 'Bachelor of national education',
                'salary' => 1000000,
                'about' => 'Guiding Students Through Time.',
                'class_level'=>'7',
                'cv'=>"/storage/images/france2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'rawan@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2022-09-09',  // Example hire date, adjust as needed
                'specialization' => 'physics and chemistry',
                'education' => 'Bachelor of physics and chemistry ',
                'salary' => 1000000,
                'about' => 'Guiding Students Through Time.',
                'class_level'=>'7',
                'cv'=>"/storage/images/social1.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'hadisabbag@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2022-09-09',  // Example hire date, adjust as needed
                'specialization' => 'music',
                'education' => 'Bachelor of music ',
                'salary' => 1000000,
                'about' => 'Guiding Students Through Time.',
                'class_level'=>'7',
                'cv'=>"/storage/images/social2.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => User::where('email', 'fesal@gmail.com')->first()->id,
                'rate' => 4.5,
                'hire_date' =>'2022-09-09',  // Example hire date, adjust as needed
                'specialization' => 'Art',
                'education' => 'Bachelor of Art ',
                'salary' => 1000000,
                'about' => 'Guiding Students Through Time.',
                'class_level'=>'7',
                'cv'=>"/storage/images/france3.pdf",
                'created_at' => now(),
                'updated_at' => now(),
            ],
                      // Add more teachers as needed
        ];

        // Insert teachers into 'teachers' table
        DB::table('teachers')->insert($teachers);
    }
}
